# Generated by Django 5.2.4 on 2025-07-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_companyprofile_individualprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=20, verbose_name='iban'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='swift',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank code (SWIFT)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_code',
            field=models.CharField(max_length=20, verbose_name='Company code'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='vat_code',
            field=models.CharField(max_length=20, verbose_name='Tax payer code'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Web site'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='individual_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Individual code'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='vat_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax payer code'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Web site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Are you a company or individual?'),
        ),
    ]
